language: php
sudo: false

jobs:
  fast_finish: true
  include:
    - php: 7.4
    - php: 8
    - php: nightly
  allow_failures:
    - php: nightly

cache:
  directories:
    - $HOME/.composer

before_install:
  - composer self-update

install:
  - composer install

script:
  - make test